[package]
name = "tesela-python"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Native Python extension for Tesela"
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
tesela = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module"] }
serde_json = { workspace = true }
serde = { workspace = true }
